### ISSUE TITLE
Blob storage

### ISSUE THREAD

**Issue by damascenorakuten** [DataDog/azure-storage-dd#4]
Hello,
I've spent some time troubleshooting the following error:
```
Traceback (most recent call last):
  File "azure_cli.py", line 23, in <module>
    args.func(args)
  File "/root/ddazurestorage/azure-storage-dd/cli/storage_azure.py", line 29, in setup_for_monitoring
    self._turn_on_minute_metrics(storage_account_name, storage_account_key, metric_table_retention_period)
  File "/root/ddazurestorage/azure-storage-dd/cli/storage_azure.py", line 42, in _turn_on_minute_metrics
    file_service.set_file_service_properties(minute_metrics=metrics)
  File "/root/ddazurestorage/lib/python2.7/site-packages/azure/storage/file/fileservice.py", line 499, in set_file_service_properties
    self._perform_request(request)
  File "/root/ddazurestorage/lib/python2.7/site-packages/azure/storage/storageclient.py", line 280, in _perform_request
    raise ex
azure.common.AzureException: ConnectionError: HTTPSConnectionPool(host='companytest.file.core.windows.net', port=443): Max retries exceeded with url: /?comp=properties&restype=service (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10b935950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

It keeps trying to connect to an inexistent file storage (Check the host) while it should be trying to connect to our blob storage. 

I had to remove the file_service and queue_service lines from **cli/storage_azure.py**:
```
        file_service = account.create_file_service()
        file_service.set_file_service_properties(minute_metrics=metrics)
        queue_service = account.create_queue_service()
        queue_service.set_queue_service_properties(minute_metrics=metrics)
```

Maybe it would be a good idea to have an option to specify the storage type, if it's file, blob, etc...

**Comment by colutti** [comment]
I am having the same issue. Does anyone have a fix for that?
